### ISSUE TITLE
Implement AbortController to createTabs system

### ISSUE THREAD

**Issue by DriftingSands** [headwire-edge-delivery/eds-self-service-website#152]
Nav bar and some this like history handlers can be messed up in the site-details tabs if switching tabs quickly.
This could likely be solved by implementing the AbortController.

**Comment by DriftingSands** [comment]
Doesn't work for our implementation without heavy refactor & specifically setup requests in the future.
It was better to just give each tab it's own tab div, and hide whichever one shouldn't be shown. This way we don't have the tabs displaying the wrong thing when rapidly switching.

**Comment by icaraps** [comment]
Fixed in https://github.com/headwire-edge-delivery/eds-self-service-website/pull/156
