### ISSUE TITLE
Campaign email issues

### ISSUE THREAD

**Issue by DriftingSands** [headwire-edge-delivery/eds-self-service-website#33]
I found a few issues with the campaign/email system while writing tests. Some previously known, some new. I thought I should list them here.

#### Major issues:
- Campaign emails are not listed, even when they are published and in query-index
- Campaign emails can't be deleted (?)
- Deleting a Campaign only deletes DB entry, does not delete drive/repo files.
- While creating an email, name is not checked if it already exists. Attempting to create an email with existing name returns unhelpful github endpoint error message.

#### Minor issues:
- Repo files have odd name: No dash/underscore/separation of campaign name & email name. 'New Campaign' and 'New email' become: `new-campaignnew-email.css`
- Campaign creation will fail with helpful error message if duplicate name is submitted. But we should check while typing. I think just comparing against the data on page load is enough though.

**Comment by icaraps** [comment]
> Campaign emails are not listed, even when they are published and in query-index

Are you sure ? Emails are listed for example here https://kestrelone.com/site/kestrelone-emails/emails/newsletters

> Campaign emails can't be deleted (?)

What do you mean ? How should it be ideally ?

**Comment by DriftingSands** [comment]
> Are you sure ? Emails are listed for example here https://kestrelone.com/site/kestrelone-emails/emails/newsletters
They appeared now, guess I didn't leave enough time for caching

> What do you mean ? How should it be ideally ?
I think there should be a delete button along with edit and open. Or do we only want emails deleted if the campaign is deleted?

**Comment by icaraps** [comment]
> They appeared now, guess I didn't leave enough time for caching

I think this should be an enhancement. Instead of relying on the query-index to list pages and emails, we can use the Drive and DA APIs. This would instantly show new pages and emails as you create them and it would avoid the caching issue.  This would also allow to differentiate previewed only vs previewed and published. 

> I think there should be a delete button along with edit and open.

Sounds like an enhancement. I think I will open a ticket for each point you described then.

**Comment by icaraps** [comment]
Closing in favor of creating multiple issues
