### ISSUE TITLE
Dark Alley Projects are not deleted correctly

### ISSUE THREAD

**Issue by Fankhauser-Dominik** [headwire-edge-delivery/eds-self-service-website#61]
The following Dark Alley Projects are not deleted correctly.
Because of this issue, it's not possible to create a new Project with this name:

- [sports-da](https://kestrelone.com/da-site/sports-da/overview)
- [wknd-da](https://kestrelone.com/da-site/wknd-da/overview)
- [wknd-dark-alley](https://kestrelone.com/da-site/wknd-dark-alley/overview)

**Comment by DriftingSands** [comment]
They keep reappearing with a single file in their DA project. I assume this is a sideeffect of how DA works, allowing you to POST to any path and it will create the folders to get to that path, thus creating the project.

I talked to Chris Miller about this a few times, one time he said they deleted them, but the reappeared the next day as usual. I don't think they entirely know what is going on either

**Comment by Fankhauser-Dominik** [comment]
I recreated the Projects and deleted them afterward.
Hopefully, they will not reappear tomorrow again.

**Comment by DriftingSands** [comment]
I'm pretty sure that won't work. I assume they will appear again tomorrow or so

**Comment by Fankhauser-Dominik** [comment]
No Project reappeared.
