### ISSUE TITLE
Projects with same name

### ISSUE THREAD

**Issue by icaraps** [headwire-edge-delivery/eds-self-service-website#68]
We have an old project named "test" that was created as a drive project that is still live at https://main--test--headwire-self-service.aem.page.

@Lauraa1003 was able to create a DA project named "test" and when previewing content changes with DA, the url https://preview--test.kestrelone.com/ would still proxy https://main--test--headwire-self-service.aem.page which holds the old content from the other "test" drive project.

**Comment by DriftingSands** [comment]
I think this issue will solve itself down the line. Currently the worker looks for a drive version(headwire-self-service) first, if that is not present it will try DA (da-self-service)

If we further implement DA we can move DA repos off the """temporary""" org and back to headwire-self-service now that it's not locked.

**Comment by icaraps** [comment]
> If we further implement DA we can move DA repos off the """temporary""" org and back to headwire-self-service now that it's not locked.

I think we should fix it sooner than later because currently, you can create a drive project, delete it, then create a DA project with the same name and your DA site will be broken because it will reference the drive project AFAIU.

**Comment by DriftingSands** [comment]
Waiting on response in the discord... Will try and fix using the EDS API, but we likely need an API key for this

**Comment by DriftingSands** [comment]
Still no response, but I had an idea that I quickly tested and it worked.

I can implement a fix for this, but it will a make the deletion request take a lot longer. We will be sending one deletion request per page. If I ever get a response there might be a way of doing it in one request

**Comment by DriftingSands** [comment]
Update frontend, backend & worker to use `da--` prefix
