### ISSUE TITLE
Unable to edit subject line in mail editor

### ISSUE THREAD

**Issue by Lauraa1003** [headwire-edge-delivery/eds-self-service-website#73]
The subject line in the mail editor is selectable but can't be edited. It should either be editable or greyed out to show it's unchangeable in the editor.
<img width="1333" alt="Screenshot 2024-10-01 at 15 59 13" src="https://github.com/user-attachments/assets/c0a1652b-332d-4a6c-9246-d18623f2fce7">

**Comment by icaraps** [comment]
PRs: 

* https://github.com/headwire-edge-delivery/eds-self-service-website/pull/83
* https://github.com/headwire-edge-delivery/eds-self-service-scripts/pull/43
