### ISSUE TITLE
Squished Mobile Layout on Admin, Account, Sites, and Tour Guide

### ISSUE THREAD

**Issue by Lauraa1003** [headwire-edge-delivery/eds-self-service-website#96]
<img width="199" alt="Screenshot 2024-10-16 at 12 25 50" src="https://github.com/user-attachments/assets/31d6ac8a-78ba-42ab-a67f-ee81ff452813">
<img width="183" alt="Screenshot 2024-10-16 at 12 20 35" src="https://github.com/user-attachments/assets/e175f80f-1704-4255-836d-68be3a913ce8">
<img width="193" alt="Screenshot 2024-10-16 at 12 16 04" src="https://github.com/user-attachments/assets/1de2020e-d7cb-4952-93a0-f2ab492f5fb5">
<img width="196" alt="Screenshot 2024-10-16 at 12 15 40" src="https://github.com/user-attachments/assets/805d4fac-38d7-4806-9cbd-e6bf839e6ae0">

**Comment by icaraps** [comment]
@Lauraa1003 Can you pls check again ? Maybe it was fixed meanwhile ?
  
<img width="330" alt="Screenshot 2024-10-16 at 15 32 26" src="https://github.com/user-attachments/assets/2ade9792-b3b9-401e-8eb0-b2b38d148458">

<img width="352" alt="Screenshot 2024-10-16 at 15 32 48" src="https://github.com/user-attachments/assets/c14c1699-49e0-49b5-8fb4-b4a77846d7ae">

<img width="360" alt="Screenshot 2024-10-16 at 15 32 15" src="https://github.com/user-attachments/assets/b4445e55-d37d-4de0-9884-49cef8ea5844">
